server {
  listen 80;

  location / {
    root   /usr/share/nginx/html;
    index  index.html;
    # Esta línea es clave: si no encuentra un archivo o directorio,
    # devuelve el index.html para que React Router maneje la ruta.
    try_files $uri $uri/ /index.html;
  }

  # Redirigir peticiones API al backend de Node.js
  location /api/ {
    proxy_pass http://172.17.0.1:3005/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    # Aumentar los tiempos de espera para peticiones largas
    proxy_connect_timeout 60s;
    proxy_send_timeout 60s;
    proxy_read_timeout 60s;
  }
}