server {
  listen 80;

  location / {
    root   /usr/share/nginx/html;
    index  index.html;
    # Esta línea es clave: si no encuentra un archivo o directorio,
    # devuelve el index.html para que React Router maneje la ruta.
    try_files $uri $uri/ /index.html;
  }

  # Redirigir peticiones API al backend de Node.js
  location /api/ {
    proxy_pass http://backend:3005/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}