server {
  listen 8080;
  client_max_body_size 0; # 0 = Sin límite de peso para subir videos

  location / {
    root   /usr/share/nginx/html;
    index  index.html;
    # Esta línea es clave: si no encuentra un archivo o directorio,
    # devuelve el index.html para que React Router maneje la ruta.
    try_files $uri $uri/ /index.html;
  }

  # Redirigir peticiones API al backend de Node.js
  location /api/ {
    proxy_pass http://127.0.0.1:3005/api/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    
    # Transmisión directa: apagar el búfer para que el video Base64 fluya directo a Node.js
    proxy_request_buffering off;
    proxy_http_version 1.1;
    proxy_set_header Connection "";

    # Aumentar los tiempos de espera para peticiones largas (24 horas)
    proxy_connect_timeout 86400s;
    proxy_send_timeout 86400s;
    proxy_read_timeout 86400s;
  }

  # Servir los videos subidos directamente
  location /uploads/ {
    proxy_pass http://127.0.0.1:3005/uploads/;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    
    # Optimización vital para streaming de video: evita que Nginx descargue todo el video en RAM antes de enviarlo
    proxy_buffering off;
    proxy_cache off;
  }
}